stages:
  - deploy

pages:
  stage: deploy
  image: 
    name: ulyssedurand/readme2html:1.0
    pull_policy: always
  script: 
    - readme2html -s . -t . -a readme/figures -g https://gitlab.com/ulysse_durand/scanner3d

    - readme2html -s scanner3dV1 -t v1 -g https://gitlab.com/ulysse_durand/scanner3d

    - readme2html -s scanner3dV2 -t v2 -g https://gitlab.com/ulysse_durand/scanner3d

    - mkdir -p public/v2nb
    - cp scanner3dV2/notebooks/main_pipeline.html public/v2nb/index.html
    - cp -r scanner3dV2/notebooks/iframe_figures public/v2nb/

  artifacts:
    paths:
      - public
