stages:
  - deploy
  - merge

pages:
  stage: deploy
  image: 
    name: ulyssedurand/readme2html:1.0
    pull_policy: always
  script: 
    - readme2html -s . -t . -a readme/figures -g https://gitlab.com/ulysse_durand/scanner3d

    - readme2html -s scanner3dV1 -t v1 -g https://gitlab.com/ulysse_durand/scanner3d

    - readme2html -s scanner3dV2 -t v2 -g https://gitlab.com/ulysse_durand/scanner3d

  artifacts:
    paths:
      - public

pagenb:
  stage: deploy
  image: jupyter/base-notebook
  script:
    - pip install -r scanner3dV2/requirements.txt
    - jupyter nbconvert scanner3dV2/notebooks/main_pipeline.ipynb --to html --output-dir=public2/v2nb --TemplateExporter.extra_template_basedirs=scanner3dV2/notebooks/ --template mytemplate --no-input --execute
    - cp -r scanner3dV2/notebooks/mytemplate/static public2/v2nb
    - mv public2/v2nb/main_pipeline.html public2/v2nb/main.html

  artifacts:
    paths:
      - public2

pagefinal:
  stage: merge
  needs: [pages, pagenb]
  script:
    - cp -r public2/ public/
  artifacts:
    paths:
      - public