  stages:
  - deploy

pages:
  stage: deploy
  image: 
    name: ulyssedurand/readme2html:1.0
    pull_policy: always
  script: 
    - readme2html . . readme/figures

    - readme2html scanner3dV1 v1

	- readme2html scanner3dV2 v2

	- mkdir -p public/v2nb
    - cp scanner3dV2/notebooks/main_pipeline.html public/v2nb/index.html
    - cp -r scanner3dV2/notebooks/iframe_figures public/v2nb/

  artifacts:
    paths:
      - public
