all: compile

compile:
	@pdflatex Scanner3D.tex
	@make clean

pdf_latex:
	@pdflatex Scanner3D.tex
	@pdflatex Scanner3D.tex
	@make clean

clean:
	@rm -f *.aux
	@rm -f *.fdb_latexmk
	@rm -f *.fls
	@rm -f *.log
	@rm -f *.lyx